# Generated by Django 3.0.7 on 2020-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.BigIntegerField()),
                ('familia', models.CharField(choices=[('Hogar', 'Hogar'), ('Viaje', 'Viaje'), ('Jugueteria', 'Jugueteria'), ('Salud y Belleza', 'Salud y Belleza'), ('Deportes', 'Deportes'), ('Licencia', 'Licencia')], default='Hogar', max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.BigIntegerField()),
                ('merma', models.BooleanField()),
                ('precio', models.BigIntegerField()),
            ],
        ),
    ]
